# fly.toml app configuration file generated for discussion-xcctgw on 2026-08-02T05:40:27Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discussion-xcctgw'
primary_region = 'nrt'

[build]

[env]
  CORS_ORIGINS = 'https://wa-ra-so.github.io'
  PYTHONUNBUFFERED = 'true'
  WHISPER_MODEL = 'base'

[[mounts]]
  source = 'discussion_data'
  destination = '/app/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
